#!/usr/bin/env bash
set -euo pipefail

# Resolve the directory this script lives in — the specs root.
SPECS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKLOG="$SPECS_DIR/00_backlog"
ACTIVE="$SPECS_DIR/01_active"
ARCHIVES="$SPECS_DIR/02_archives"
INDEX="$SPECS_DIR/INDEX.md"

die() { echo "specs.sh: $*" >&2; exit 1; }

valid_slug() {
  [[ "$1" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]] || die "invalid slug '$1' (use kebab-case: a-z 0-9 -)"
}

# Comma-joined list of artifact files present in a topic folder.
artifacts() {
  local dir="$1" a labels=()
  for a in design plan notes spec; do
    [[ -f "$dir/$a.md" ]] && labels+=("$a")
  done
  local IFS=,
  echo "${labels[*]}"
}

# Print the `shipped:` frontmatter value from a folder's design.md/spec.md (empty if none).
shipped_date() {
  local dir="$1" f
  for f in "$dir/design.md" "$dir/spec.md"; do
    if [[ -f "$f" ]]; then
      awk -F': *' '/^shipped:/ { print $2; exit }' "$f"
      return
    fi
  done
}

# Insert `shipped: <today>` into a file's frontmatter (creating a block if absent).
stamp_shipped() {
  local f="$1" today
  today="$(date +%F)"
  grep -q '^shipped:' "$f" && return 0
  if head -1 "$f" | grep -qx -- '---'; then
    awk -v d="$today" 'NR==1 && $0=="---" { print; print "shipped: " d; next } { print }' \
      "$f" > "$f.tmp" && mv "$f.tmp" "$f"
  else
    { echo "---"; echo "shipped: $today"; echo "---"; echo; cat "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
  fi
}

cmd_index() {
  {
    echo "# Specs Index"
    echo
    echo "_Generated by specs.sh — do not edit by hand._"
    echo
    echo "## Active"
    if compgen -G "$ACTIVE/*/" >/dev/null; then
      for d in "$ACTIVE"/*/; do
        d="${d%/}"; local slug; slug="$(basename "$d")"
        echo "- [$slug](01_active/$slug/) — $(artifacts "$d")"
      done
    else
      echo "_none_"
    fi
    echo
    echo "## Backlog"
    local any=0
    if compgen -G "$BACKLOG/*/" >/dev/null; then
      for d in "$BACKLOG"/*/; do
        d="${d%/}"; local slug; slug="$(basename "$d")"
        echo "- [$slug](00_backlog/$slug/) — $(artifacts "$d")"
        any=1
      done
    fi
    if compgen -G "$BACKLOG/*.md" >/dev/null; then
      for f in "$BACKLOG"/*.md; do
        local slug; slug="$(basename "$f" .md)"
        echo "- [$slug](00_backlog/$slug.md)"
        any=1
      done
    fi
    [[ $any -eq 0 ]] && echo "_none_"
    echo
    echo "## Done"
    if compgen -G "$ARCHIVES/*/" >/dev/null; then
      for d in "$ARCHIVES"/*/; do
        d="${d%/}"; local slug sd; slug="$(basename "$d")"; sd="$(shipped_date "$d")"
        if [[ -n "$sd" ]]; then
          echo "- [$slug](02_archives/$slug/) — shipped $sd"
        else
          echo "- [$slug](02_archives/$slug/) — $(artifacts "$d")"
        fi
      done
    else
      echo "_none_"
    fi
  } > "$INDEX"
  echo "Wrote $INDEX"
}

cmd_new() {
  local slug="${1:-}" title="${2:-}"
  [[ -n "$slug" ]] || die 'usage: specs.sh new <slug> ["title"]'
  valid_slug "$slug"
  [[ -e "$BACKLOG/$slug.md" || -e "$BACKLOG/$slug" || -e "$ACTIVE/$slug" || -e "$ARCHIVES/$slug" ]] \
    && die "slug '$slug' already exists"
  [[ -n "$title" ]] || title="$(echo "$slug" | tr '-' ' ')"
  mkdir -p "$BACKLOG"
  cat > "$BACKLOG/$slug.md" <<EOF
---
title: $title
created: $(date +%F)
---

<what>. <why>.
Ref:
Size: S
EOF
  echo "Created $BACKLOG/$slug.md"
  cmd_index
}

case "${1:-}" in
  new)   shift; cmd_new "$@" ;;
  index) cmd_index ;;
  *)     die "usage: specs.sh {new|activate|archive|index}" ;;
esac
